name: Manual Release

on:
    workflow_dispatch:
      inputs:
        version:
          type: string
          description: BYOND Version
          required: true
        beta:
          type: boolean
          description: This release is a beta build

env:
  BYOND_VERSION: ""
  BYOND_MAJOR_VERSION: ""
  BYOND_MINOR_VERSION: ""
  IMAGE_NAME: ${{ github.repository }}


jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Setup the build environment"
        run: |
          BYOND_VERSION="${{ github.event.inputs.version }}"
          BYOND_MAJOR_VERSION="$(echo "$(cut -d '.' -f 1 <(echo "$BYOND_VERSION"))")"
          BYOND_MINOR_VERSION="$(echo "$(cut -d '.' -f 2 <(echo "$BYOND_VERSION"))")"
          echo "BYOND_VERSION="$BYOND_VERSION"" >> $GITHUB_ENV
          echo "BYOND_MAJOR_VERSION="$BYOND_MAJOR_VERSION"" >> $GITHUB_ENV
          echo "BYOND_MINOR_VERSION="$BYOND_MINOR_VERSION"" >> $GITHUB_ENV
      
      - name: Login to the Docker Hub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check if the release was already published to the Docker Registry
        id: docker_release_check
        continue-on-error: true
        run: |
          docker manifest inspect douglasparker/byond:${{ env.BYOND_VERSION }}
      
      - name: Build the Docker image and publish to the Docker Registry
        uses: docker/build-push-action@v3
        if: steps.docker_release_check.outcome == 'failure'
        with:
          context: .
          push: true
          build-args: |
            BYOND_MAJOR=${{ env.BYOND_MAJOR_VERSION }}
            BYOND_MINOR=${{ env.BYOND_MINOR_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.BYOND_VERSION }}