name: Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      version:
        description: The BYOND Version that you want to release.

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check for latest BYOND version
        run: |
          if [ -z "${{ github.event.inputs.server }}" ]; then
            cat "${{ github.event.inputs.server }}" > VERSION
          else
            curl https://secure.byond.com/download/version.txt -o VERSION
          fi

      - name: Build docker images
        run: |
          docker build --build-arg BYOND_MAJOR=$(echo "$(cut -d'.' -f1 <<< $(cat ${{ github.workspace }}/VERSION))") --build-arg BYOND_MINOR=$(echo "$(cut -d'.' -f2 <<< $(cat ${{ github.workspace }}/VERSION))") -t douglasparker/byond:$(cat ${{ github.workspace }}/VERSION) -t douglasparker/byond:latest -t ghcr.io/douglasparker/byond:$(cat ${{ github.workspace }}/VERSION) -t ghcr.io/douglasparker/byond:latest .
      
      - name: Save docker images
        run: |
          docker save --output ${{ github.workspace }}/images.tar douglasparker/byond:$(cat ${{ github.workspace }}/VERSION) douglasparker/byond:latest ghcr.io/douglasparker/byond:$(cat ${{ github.workspace }}/VERSION) ghcr.io/douglasparker/byond:latest

      - name: Cache build artifacts
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/VERSION
            ${{ github.workspace }}/images.tar
          key: $(cat ${{ github.workspace }}/VERSION)
  
  Release:
    runs-on: ubuntu-20.04
    needs: [Build]
    steps:
      - name: Restore cached build artifacts
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/VERSION
            ${{ github.workspace }}/images.tar
          key: $(cat ${{ github.workspace }}/VERSION)
      
      - name: Load docker images
        run: |
          docker load --input ${{ github.workspace }}/images.tar
      
      - name: Publish releases to Docker Hub
        run: |
          docker login -u "${{ secrets.DOCKER_REGISTRY_USERNAME }}" -p "${{ secrets.DOCKER_REGISTRY_PASSWORD }}"
          docker push douglasparker/byond:$(cat ${{ github.workspace }}/VERSION)
          docker push douglasparker/byond:latest
      
      - name: Publish releases to GitHub Container Registry
        run: |
          docker login ghcr.io -u "${{ secrets.GH_CONTAINER_REGISTRY_USERNAME }}" -p "${{ secrets.GH_CONTAINER_REGISTRY_PASSWORD }}"
          docker push ghcr.io/douglasparker/byond:$(cat ${{ github.workspace }}/VERSION)
          docker push ghcr.io/douglasparker/byond:latest
