name: Release

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Check for latest BYOND version
        run: |
          curl https://secure.byond.com/download/version.txt -o VERSION

      - name: Build docker images
        run: |
          docker build --build-arg BYOND_MAJOR=$(echo "$(cut -d'.' -f1 <<< $(cat ${{ github.workspace }}/VERSION))") --build-arg BYOND_MINOR=$(echo "$(cut -d'.' -f2 <<< $(cat ${{ github.workspace }}/VERSION))") -t douglasparker/byond:$(cat ${{ github.workspace }}/VERSION) -t douglasparker/byond:latest .
      
      - name: Save docker images
        run: |
          docker save --output ${{ github.workspace }}/images.tar douglasparker/byond:$(cat ${{ github.workspace }}/VERSION) douglasparker/byond:latest

      - name: Cache build artifacts
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/VERSION
            ${{ github.workspace }}/images.tar
          key: ${{ github.sha }}
  
  Release:
    runs-on: ubuntu-20.04
    needs: [Build]
    steps:
      - name: Restore cached build artifacts
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ${{ github.workspace }}/VERSION
            ${{ github.workspace }}/images.tar
          key: ${{ github.sha }}
      
      - name: Load docker images
        run: |
          docker load --input ${{ github.workspace }}/images.tar
      
      - name: Publish releases to Docker Hub
        run: |
          docker login -u "${{ secrets.REGISTRY_USERNAME }}" -p "${{ secrets.REGISTRY_PASSWORD }}"
          docker push douglasparker/byond:$(cat ${{ github.workspace }}/VERSION)
          docker push douglasparker/byond:latest