name: Release

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

env:
  BYOND_VERSION: ""
  BYOND_MAJOR_VERSION: ""
  BYOND_MINOR_VERSION: ""
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Check for the latest BYOND version
        run: |
          curl https://secure.byond.com/download/version.txt -o BYOND_VERSION
          echo "BYOND_VERSION=$(cat BYOND_VERSION)" >> $GITHUB_ENV
          echo "BYOND_MAJOR_VERSION=$(echo "$(cut -d'.' -f1 ${{ github.workspace }}/BYOND_VERSION)")" >> $GITHUB_ENV
          echo "BYOND_MINOR_VERSION=$(echo "$(cut -d'.' -f2 ${{ github.workspace }}/BYOND_VERSION)")" >> $GITHUB_ENV
      
      - name: Login to the Docker Hub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to the GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Check if this release was already published to the Docker Registry
        id: docker_check
        continue-on-error: true
        run: |
          docker manifest inspect douglasparker/byond:${{ env.BYOND_VERSION }}
      
      - name: Build the Docker image and publish to the Docker Registry
        uses: docker/build-push-action@v3
        if: steps.docker_check.outcome == 'failure'
        with:
          context: .
          push: true
          build-args: |
            BYOND_MAJOR=${{ env.BYOND_MAJOR_VERSION }}
            BYOND_MINOR=${{ env.BYOND_MINOR_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.BYOND_MAJOR_VERSION }}
            ${{ env.IMAGE_NAME }}:${{ env.BYOND_VERSION }}
            ghcr.io/${{ env.IMAGE_NAME }}:latest
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.BYOND_MAJOR_VERSION }}
            ghcr.io/${{ env.IMAGE_NAME }}:${{ env.BYOND_VERSION }}

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
