name: Release

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

env:
  BYOND_VERSION: ""
  BYOND_MAJOR_VERSION: ""
  BYOND_MINOR_VERSION: ""
  BYOND_BETA_VERSION: ""
  BYOND_BETA_MAJOR_VERSION: ""
  BYOND_BETA_MINOR_VERSION: ""
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Check for the latest version of BYOND
        run: |
          BYOND_VERSION="$(sed -n 1p <(curl https://secure.byond.com/download/version.txt))"
          BYOND_MAJOR_VERSION="$(echo "$(cut -d '.' -f 1 <(echo "$BYOND_VERSION"))")"
          BYOND_MINOR_VERSION="$(echo "$(cut -d '.' -f 2 <(echo "$BYOND_VERSION"))")"
          echo "BYOND_VERSION="$BYOND_VERSION"" >> $GITHUB_ENV
          echo "BYOND_MAJOR_VERSION="$BYOND_MAJOR_VERSION"" >> $GITHUB_ENV
          echo "BYOND_MINOR_VERSION="$BYOND_MINOR_VERSION"" >> $GITHUB_ENV
      
      - name: Check for the latest beta version of BYOND
        run: |
          BYOND_BETA_VERSION="$(sed -n 2p <(curl https://secure.byond.com/download/version.txt))"
          BYOND_BETA_MAJOR_VERSION="$(echo "$(cut -d '.' -f 1 <(echo "$BYOND_BETA_VERSION"))")"
          BYOND_BETA_MINOR_VERSION="$(echo "$(cut -d '.' -f 2 <(echo "$BYOND_BETA_VERSION"))")"
          echo "BYOND_BETA_VERSION="$BYOND_BETA_VERSION"" >> $GITHUB_ENV
          echo "BYOND_BETA_MAJOR_VERSION="$BYOND_BETA_MAJOR_VERSION"" >> $GITHUB_ENV
          echo "BYOND_BETA_MINOR_VERSION="$BYOND_BETA_MINOR_VERSION"" >> $GITHUB_ENV
      
      - name: Login to the Docker Hub Registry
        uses: docker/login-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Check if the stable release was already published to the Docker Registry
        id: docker_stable_release_check
        continue-on-error: true
        run: |
          docker manifest inspect douglasparker/byond:${{ env.BYOND_VERSION }}
      
      - name: Check if the beta release was already published to the Docker Registry
        id: docker_beta_release_check
        continue-on-error: true
        run: |
          docker manifest inspect douglasparker/byond:${{ env.BYOND_BETA_VERSION }}-beta
      
      - name: \[Stable] Build the Docker image and publish to the Docker Registry
        uses: docker/build-push-action@v3
        if: steps.docker_stable_release_check.outcome == 'failure'
        with:
          context: .
          push: true
          build-args: |
            BYOND_MAJOR=${{ env.BYOND_MAJOR_VERSION }}
            BYOND_MINOR=${{ env.BYOND_MINOR_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ env.BYOND_MAJOR_VERSION }}
            ${{ env.IMAGE_NAME }}:${{ env.BYOND_VERSION }}
      
      - name: \[Beta] Build the Docker image and publish to the Docker Registry
        uses: docker/build-push-action@v3
        if: steps.docker_beta_release_check.outcome == 'failure'
        with:
          context: .
          push: true
          build-args: |
            BYOND_MAJOR=${{ env.BYOND_BETA_MAJOR_VERSION }}
            BYOND_MINOR=${{ env.BYOND_BETA_MINOR_VERSION }}
          tags: |
            ${{ env.IMAGE_NAME }}:beta
            ${{ env.IMAGE_NAME }}:${{ env.BYOND_BETA_MAJOR_VERSION }}-beta
            ${{ env.IMAGE_NAME }}:${{ env.BYOND_BETA_VERSION }}-beta

      - name: Update Docker Hub Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
